function [extension,formatName] = selectFiletype(numFrames)

  %Estimated file sizes in order: mj2-compressed, mj2, mj2-avi, avi, mp4
  sizes = {numFrames*104.264,numFrames*285.286,numFrames*30.849,
           numFrames*1043.562,...
           numFrames*0.562};
	       %numFrames*284,...
           %numFrames*284,numFrames*284};

  defaultFormat = 1;

  formatDescs = {strcat('Motion JPEG 2000 (.mj2) Compressed ',...
                        ' [',num2str(sizes{1}),'kb]'),...
                 strcat('Archival (.mj2) lossless Motion JPEG 2000 compression ',...
                        ' [',num2str(sizes{2}),'kb]'),...
                 strcat('Motion JPEG AVI (.avi) Compressed using Motion JPEG ',...
                        ' [',num2str(sizes{3}),'kb]'),...
                 strcat('Uncompressed (.avi) with RGB24 video ',...
                        ' [',num2str(sizes{4}),'kb]'),...
                 strcat('MPEG-4 (.mp4) Compressed H.264 encoding (Win7/MacOS 10.7) ',...
                        ' [',num2str(sizes{5}),'kb]')};
                 %       ' [',num2str(sizes{5}),'kb]'),...
                 %strcat('Grayscale (.avi) Uncompressed (Monochrome devices only) ',...
                 %       ' [',num2str(sizes{6}),'kb]'),...
                 %strcat('Indexed (.avi) Uncompressed (Monochrome devices only) ',...
                 %       ' [',num2str(sizes{7}),'kb]')};

  formatNames = {'Motion JPEG 2000',...
                 'Archival',...
                 'Motion JPEG AVI',...
                 'Uncompressed AVI',...
                 'MPEG-4'};
                 %'MPEG-4',...
                 %'Grayscale AVI',...
                 %'Indexed AVI'};

  formatExtensions = {'.mj2',...
                      '.mj2',...
                      '.avi',...
                      '.avi',...
                      '.mp4'};
                      %'.mp4',...
                      %'.avi',...
                      %'.avi'};

  s = 0;
  v = 0;
  prompt = 'Select video format [estimated size]';
  bad_prompt = 'Select video format [estimated size] **A selection is required';
  tmp_prompt = prompt;
  while v == 0
    [s,v] = listdlg('PromptString',tmp_prompt,...
                    'SelectionMode','single',...
                    'ListSize',[400 140],...
                    'InitialValue',defaultFormat,...
                    'ListString',formatDescs);
    tmp_prompt = bad_prompt;
  end

  extension = formatExtensions{s};
  formatName = formatNames{s};

end
